Jeet/config/routes.rb
Rails.application.routes.draw do
  get 'question/index'

  get 'question/show'

  get 'question/new'

  get 'question/edit'

  get 'question/delete'

  get 'question/error'
  
  get 'sessions/new'

  resources :users
  resources :food_classes
  resources :food_types
  resources :questions
  resources :allusers
  resources :restaurants
  resources :reviews

  root 'welcome#index'

  get 'question' => 'question#index'
  get 'search' => 'question#search'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

Jeet/app/models/alluser.rb
class Alluser < ActiveRecord::Base
end

Jeet/app/models/food_class.rb
class FoodClass < ActiveRecord::Base
end

Jeet/app/models/question.rb
class Question < ActiveRecord::Base
end

Jeet/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

Jeet/app/models/review.rb
class Review < ActiveRecord::Base
end

Jeet/app/models/user.rb
class User < ActiveRecord::Base

	validates :username, presence: true, uniqueness: {case_sensitive: true}
	validates :email, presence: true, uniqueness: {case_sensitive: true}
	validates :password, presence: true, length: {maximum: 20}
	has_secure_password

end

Jeet/app/controllers/allusers_controller.rb
class AllusersController < ApplicationController
end

Jeet/app/controllers/food_classes_controller.rb
class FoodClassesController < ApplicationController
  before_action :set_food_class, only: [:show, :edit, :update, :destroy]

  # GET /food_classes
  # GET /food_classes.json
  def index
    @food_classes = FoodClass.all
  end

  # GET /food_classes/1
  # GET /food_classes/1.json
  def show
  end

  # GET /food_classes/new
  def new
    @food_class = FoodClass.new
  end

  # GET /food_classes/1/edit
  def edit
  end

  # POST /food_classes
  # POST /food_classes.json
  def create
    @food_class = FoodClass.new(food_class_params)

    respond_to do |format|
      if @food_class.save
        format.html { redirect_to @food_class, notice: 'Food class was successfully created.' }
        format.json { render :show, status: :created, location: @food_class }
      else
        format.html { render :new }
        format.json { render json: @food_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_classes/1
  # PATCH/PUT /food_classes/1.json
  def update
    respond_to do |format|
      if @food_class.update(food_class_params)
        format.html { redirect_to @food_class, notice: 'Food class was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_class }
      else
        format.html { render :edit }
        format.json { render json: @food_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_classes/1
  # DELETE /food_classes/1.json
  def destroy
    @food_class.destroy
    respond_to do |format|
      format.html { redirect_to food_classes_url, notice: 'Food class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_class
      @food_class = FoodClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_class_params
      params.require(:food_class).permit(:name)
    end
end

Jeet/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

Jeet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

Jeet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end

end

Jeet/app/helpers/allusers_helper.rb
module AllusersHelper
end

Jeet/app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
    	base_title = "Jeet"
    	if page_title.empty?
      		base_title
    	else
      		"#{page_title} | #{base_title}"
    	end
  	end

end

Jeet/app/helpers/food_classes_helper.rb
module FoodClassesHelper
end

Jeet/app/helpers/food_types_helper.rb
module FoodTypesHelper
end

Jeet/app/helpers/question_helper.rb
module QuestionHelper
	
end

Jeet/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

Jeet/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Jeet/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

Jeet/app/helpers/users_helper.rb
module UsersHelper
end

Jeet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Jeet/app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

Jeet/app/views/food_classes/_form.html.erb
<%= form_for(@food_class) do |f| %>
  <% if @food_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_class.errors.count, "error") %> prohibited this food_class from being saved:</h2>

      <ul>
      <% @food_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Jeet/app/views/food_classes/edit.html.erb
<h1>Editing Food Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_class %> |
<%= link_to 'Back', food_classes_path %>

Jeet/app/views/food_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_classes.each do |food_class| %>
      <tr>
        <td><%= food_class.name %></td>
        <td><%= link_to 'Show', food_class %></td>
        <td><%= link_to 'Edit', edit_food_class_path(food_class) %></td>
        <td><%= link_to 'Destroy', food_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food class', new_food_class_path %>

Jeet/app/views/food_classes/new.html.erb
<h1>New Food Class</h1>

<%= render 'form' %>

<%= link_to 'Back', food_classes_path %>

Jeet/app/views/food_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_class.name %>
</p>

<%= link_to 'Edit', edit_food_class_path(@food_class) %> |
<%= link_to 'Back', food_classes_path %>